SELECT ?item ?startdate ?enddate WHERE {
  ?item wdt:P31 wd:Q5;
        p:P39 ?posStatement .
  
  ?posStatement ps:P39 wd:Q10655178;
                pq:P580 ?startdate.
  OPTIONAL { ?posStatement pq:P582 ?enddate }
}